# Site Settings
title: A SVG Site

# Build Settings
markdown: kramdown
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions

# Customize the theme
show_downloads: false

# My SEO
# ToDo: Create new GA-ID
google_analytics: UA-61449151-2

# My collections
collections:
  samples:
    output: true
  mypages:
    output: true
  blocks:
    output: true
  
# Layout Settings
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Marco M. von Hagen"
      codename: "m2vh"
      
# Hide the READMEs
exclude:
  - "/*/README.md"

# My SASS
# Bootstrap v3.3.7

sass:
  style: :compressed
  
